apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels: #labels serve para atribuir um pod a um service atraves de um selector
    app: segundo-pod
spec:
  containers:
    - name: container-pod-2
      image: nginx:latest
      ports: 
        - containerPort: 80