apiVersion: v1
kind: Pod 
metadata:
  name: portal-noticias
  labels:
    app: portal-noticias # label para fazer bind com service
spec:
  containers:
    - name: portal-noticias-container
      image: aluracursos/portal-noticias:1
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: portal-configmap