# o pod esta na versao stable da api Vx
apiVersion: v1
# o tipo do recurso que a gente quer criar é um pod
kind: Pod
metadata:
  name: primeiro-pod-declarativo
spec:
  containers:
    - name: nginx-container
      image: nginx:stable
