apiVersion: v1
kind: Pod
metadata:
  name: sistema-noticias
  labels:
    app: sistema-noticias
spec:
  containers:
    - name: sistema-noticias-container
      image: aluracursos/sistema-noticias:1
      ports:
      - containerPort: 80
      envFrom: #Importando todas as variáveis do configmap neste pod
        - configMapRef:
            name: sistema-configmap