apiVersion: v1
kind: ConfigMap
metadata:
  name: sistema-configmap
data:  #no HOST_DB utilizei o dns que peguei com o comando (kubectl get svc -o wide)
  HOST_DB: svc-db-noticias:3306
  USER_DB: root 
  PASS_DB: q1w2e3r4
  DATABASE_DB: empresa 
  
