apiVersion: v1
kind: Service
metadata:
  name: svc-pod-2
spec:
  type: ClusterIP
  selector:
    app: segundo-pod # pod que o svc escuta que foi declarado na label do pod
  ports:
    - port: 9000 #porta que o svc recebe a requisição
      targetPort: 80 #porta do pod para despachar a requisição
