apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  type: NodePort
  ports:
    - port:  80 #quando recebe a requisiçao na porta 80 encaminha para a 80 pois se não tem target esta implicito
    # targetPort:  8080
      nodePort: 30000 # range permitido de 30.000 ate 32.767
  selector:
    app: portal-noticias #selector faz bind com label do outro pod
