apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  ports:
    - port: 80 #port e target port serão iguais implicitamente se não definirmos o targetPort
    #  targetPort: 8080
      nodePort: 30000 # porta de acesso externo que pode ser de 30000 ate 32767
  selector:
    app: primeiro-pod #faz o bind com a label de um pod